title: Finch
optionalCategoryIndex: true
supportedLanguages: []
properties: []
relatedLinks: []
name: Finch_help
repositoryName: Finch_help
sourceName: github.com
userInfo:
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
logo: logo.svg
lfs:
  auto: false
  exclude: []
logo_dark: logo_dark.svg
